## 1. Data Understanding



#### - Understand what your data resources are and what the characteristics of those resources are. Write down your findings including the characteristics of the different columns in the dataset.

In [31]:
import pandas as pd
import numpy as np

In [32]:
data = pd.read_csv('student.csv')
data.head(3)

school sex  age address famsize Pstatus                           Medu  \
0     GP   F   18       U     GT3       A               higher education   
1     GP   F   17       U     GT3       T  primary education (4th grade)   
2     GP   F   15       U     LE3       T  primary education (4th grade)   

                            Fedu     Mjob     Fjob  ...     famrel freetime  \
0               higher education  at_home  teacher  ...  very good   medium   
1  primary education (4th grade)  at_home    other  ...  excellent   medium   
2  primary education (4th grade)  at_home    other  ...  very good   medium   

    goout      Dalc      Walc health absences G1 G2  G3  
0    high  very low  very low   good        6  5  6   6  
1  medium  very low  very low   good        4  5  5   6  
2     low       low    medium   good       10  7  8  10  

[3 rows x 33 columns]

In [33]:
print(data['sex'].unique())
print(data.dtypes['sex'])

['F' 'M']
object


In [34]:
print(data['sex'].unique())
print(data.dtypes['sex'])

['F' 'M']
object


In [35]:
print(data['age'].unique())
print(data.dtypes['age'])

[18 17 15 16 19 22 20 21]
int64


In [36]:
print(data['address'].unique())
print(data.dtypes['address'])

['U' 'R']
object


In [37]:
print(data['famsize'].unique())
print(data.dtypes['famsize'])

['GT3' 'LE3']
object


In [39]:
print(data['Pstatus'].unique())
print(data.dtypes['Pstatus'])

['A' 'T']
object


In [40]:
print(data['Medu'].unique())
print(data.dtypes['Medu'])

['higher education' 'primary education (4th grade)' 'secondary education'
 '5th to 9th grade' 'none']
object


In [41]:
print(data['Fedu'].unique())
print(data.dtypes['Fedu'])

['higher education' 'primary education (4th grade)' '5th to 9th grade'
 'secondary education' 'none']
object


In [42]:
print(data['Mjob'].unique())
print(data.dtypes['Mjob'])

['at_home' 'health' 'other' 'services' 'teacher']
object


In [43]:
print(data['Fjob'].unique())
print(data.dtypes['Fjob'])

['teacher' 'other' 'services' 'health' 'at_home']
object


In [44]:
print(data['reason'].unique())
print(data.dtypes['reason'])

['course' 'other' 'home' 'reputation']
object


In [45]:
print(data['guardian'].unique())
print(data.dtypes['guardian'])

['mother' 'father' 'other']
object


In [ ]:
print(data['guardian'].unique())
print(data.dtypes['guardian'])

In [46]:
print(data['traveltime'].unique())
print(data.dtypes['traveltime'])

['15 to 30 min.' '<15 min.' '30 min. to 1 hour' '>1 hour']
object


In [47]:
print(data['studytime'].unique())
print(data.dtypes['studytime'])

['2 to 5 hours' '5 to 10 hours' '<2 hours' '>10 hours']
object


In [48]:
print(data['failures'].unique())
print(data.dtypes['failures'])

[0 3 2 1]
int64


In [49]:
print(data['schoolsup'].unique())
print(data.dtypes['schoolsup'])

['yes' 'no']
object


In [50]:
print(data['famsup'].unique())
print(data.dtypes['famsup'])

['no' 'yes']
object


In [51]:
print(data['paid'].unique())
print(data.dtypes['paid'])

['no' 'yes']
object


In [52]:
print(data['activities'].unique())
print(data.dtypes['activities'])

['no' 'yes']
object


In [53]:
print(data['nursery'].unique())
print(data.dtypes['nursery'])

['yes' 'no']
object


In [54]:
print(data['higher'].unique())
print(data.dtypes['higher'])

['yes' 'no']
object


In [55]:
print(data['internet'].unique())
print(data.dtypes['internet'])

['no' 'yes']
object


In [56]:
print(data['romantic'].unique())
print(data.dtypes['romantic'])

['no' 'yes']
object


In [57]:
print(data['famrel'].unique())
print(data.dtypes['famrel'])

['very good' 'excellent' 'good' 'very bad' 'bad']
object


In [58]:
print(data['freetime'].unique())
print(data.dtypes['freetime'])

['medium' 'low' 'high' 'very low' 'very high']
object


In [59]:
print(data['goout'].unique())
print(data.dtypes['goout'])

['high' 'medium' 'low' 'very low' 'very high']
object


In [60]:
print(data['Dalc'].unique())
print(data.dtypes['Dalc'])

['very low' 'low' 'very high' 'medium' 'high']
object


In [61]:
print(data['Walc'].unique())
print(data.dtypes['Walc'])

['very low' 'medium' 'low' 'high' 'very high']
object


In [62]:
print(data['health'].unique())
print(data.dtypes['health'])

['good' 'excellent' 'very bad' 'bad' 'very good']
object


In [72]:
print(data['absences'].unique())
print(data.dtypes['absences'])

[ 6  4 10  2  0 16 14  7  8 25 12 54 18 26 20 56 24 28  5 13 15 22  3 21
  1 75 30 19  9 11 38 40 23 17]
int64


In [73]:
print(data['G1'].unique())
print(data.dtypes['G1'])

[ 5  7 15  6 12 16 14 10 13  8 11  9 17 19 18  4  3]
int64
